<?php
$title = 'User List';
$this->headTitle($title);
$i = 1;
?>
<h1><?php echo $this->escapeHtml($title); ?> </h1>
<p>
	<a href = "<?php echo $this->url('user/add', array('action' => 'add'));?>">Add New User</a>
</p>

<table class="table">
	<tr>
		<th>#</th>
		<th>Name</th>
		<th>User Name</th-->
		<th>Contact Number</th>
		<th>E-mail Id</th>
		<th>Designation</th>
		<!--th>Description</th-->
		<th>Profile Image</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>


	<?php foreach($this->users as $user){ 
	?>
		<tr>
			<td ><?php echo $i;?></td>
			<td><?php echo $this->escapeHtml($user->getFirst_name()).' '.$this->escapeHtml($user->getLast_name()); ?> </td>
			<td><?php echo $this->escapeHtml($user->getUser_name()); ?> </td>
			<td><?php echo $this->escapeHtml($user->getContact_num());?></td>
			<td><?php echo $this->escapeHtml($user->getEmail()); ?> </td>
			<td><?php echo $this->escapeHtml($user->getDesignation());?></td>
			<!--td><?php //echo $this->escapeHtml($user->getDescription());?></td-->
			<td><?php echo $this->escapeHtml($user->getProfile_pic());?>
			</td>
			<td><a href = "<?php echo $this->url('user/edit', array('id' => $user->getId() )); ?>">Edit</a></td>
			<td><a href = "<?php echo $this->url('user/delete', array('id' => $user->getId() )); ?>">Delete</a></td>
		</tr>
	<?php
	$i++;
	} 
?>
</table>