<?php
$title = 'User List';
$this->headTitle($title);
$i = 1;
?>
<h1><?php echo $this->escapeHtml($title); ?> </h1>
<p>
	<a href = "<?php echo $this->url('user', array('action' => 'add'));?>">Add New User</a>
</p>

<table class="table">
	<tr>
		<th>#</th>
		<th>Name</th>
		<th>Contact Number</th>
		<th>E-mail Id</th>
		<th>Designation</th>
		<th>Profile Image</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>


	<?php foreach($this->users as $user){ 
	?>
		<tr>
			<td ><?php echo $i;?></td>
			<td><?php echo $this->escapeHtml($user->getName()); ?> </td>
			<td><?php echo $this->escapeHtml($user->getContact());?></td>
			<td><?php echo $this->escapeHtml($user->getEmail()); ?> </td>
			<td><?php echo $this->escapeHtml($user->getDesignation());?></td>
			<td><?php echo $this->escapeHtml($user->getProfilePic());?></td>
			<td><a href = "<?php echo $this->url('user', array('action' => 'edit', 'id' => $user->getId() )); ?>">Edit</a></td>
			<td><a href = "<?php echo $this->url('user', array('action' => 'delete', 'id' => $user->getId() )); ?>">Delete</a></td>
		</tr>
	<?php
	$i++;
	} 
?>
</table>