<!-- Filename: /module/Blog/view/blog/list/index.phtml -->
<?php
$title = 'Blog List';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?> </h1>
<p>
	<a href = "<?php echo $this->url('blog', array('action' => 'add'));?>">Add new blog</a>
</p>

<?php /*foreach($this->posts as $post){ ?>
	<article>
	<h1 id="post<?php echo $post->getId() ?>"><?php echo $post->getTitle() ?></h1>
	<p>
	<?php echo $post->getText() ?>
	</p>
	</article>
<?php }*/ ?>


<table class="table">
	<tr>
		<th>Title</th>
		<th>Detail</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
<?php foreach($this->posts as $post) : ?>
	<tr>
		<td><?php echo $this->escapeHtml($post->getTitle()); ?> </td>
		<td><?php echo $this->escapeHtml($post->getText()); ?> </td>
		<td>
			<a href = "<?php echo $this->url('blog', array('action' => 'edit', 'id' => $post->getId())); ?>">Edit</a>
		</td>
		<td>	
			<a href = "<?php echo $this->url('blog', array('action' => 'delete', 'id' => $post->getId() )); ?>">Delete</a>
		</td>
		
	</tr>
	<?php endforeach; ?>
</table>
