<?php
$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?> </h1>
<p>
	<a href = "<?php echo $this->url('album', array('action' => 'add'));?>">Add new album</a>
</p>

<table class="table">
	<tr>
		<th>Title</th>
		<th>Artist</th>
		<th>Added By</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
	<?php foreach($albums as $album) : ?>
	<tr>
		<td><?php echo $this->escapeHtml($album->title); ?> </td>
		<td><?php echo $this->escapeHtml($album->artist); ?> </td>
		<td><?php echo $this->escapeHtml($album->user_id); ?> </td>
		<td>
			<a href = "<?php echo $this->url('album', array('action' => 'edit', 'id' => $album->id)); ?>">Edit</a>
		</td>
		<td>	
			<a href = "<?php echo $this->url('album', array('action' => 'delete', 'id' => $album->id )); ?>">Delete</a>
		</td>
		
	</tr>
	<?php endforeach; ?>
</table>