<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
	    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('album') ?>"><?php echo $this->translate('Album') ?></a></li>
						<li class=""><a href="<?php echo $this->url('blog') ?>"><?php echo $this->translate('Blog') ?></a></li>
						<li class=""><a href="<?php echo $this->url('user') ?>"><?php echo $this->translate('Users') ?></a></li>
						<!--li class="active"><a href="<?php //echo $this->url('user') ?>"><?php //echo $this->translate('My Profile') ?></a></li-->
                    </ul>
					<ul class="nav navbar-nav navbar-right"> 
						<li class=""><a href="<?php echo $this->url('user/add') ?>"><?php echo $this->translate('Sign Up') ?></a></li>
						<li class=""><a href="<?php echo $this->url('user') ?>"><?php echo $this->translate('Login') ?></a></li>
						<?php /*
						<li><a>Welcome Admin</a></li>
						<li class="dropdown">
							<a id="user-settings" data-step="4" data-intro="You can Set up settings here" href="#" data-toggle="dropdown" class="dropdown-toggle active">
								<i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>Action
							</a>
							<ul class="dropdown-menu">                        
								<li>
									<a href="http://icm.local/index.php/Login/logout"><!--i class="fa fa-sign-out fa-fw"></i--> Change Password</a>
								</li>
								<li class="">                    
									<a href="#">
										<!--i class="fa fa-edit "></i--> Edit Profile 
									</a>                             
								</li>
								<li>
									<a href="http://icm.local/index.php/Login/logout"><!--i class="fa fa-sign-out fa-fw"></i--> Logout</a>
								</li>
								*/ ?>
							</ul>
							<!-- /.dropdown-user -->
						</li>
						<!-- /.dropdown -->
					</ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
